### ISSUE TITLE
TypeError: Cannot read property 'total' of null

### ISSUE THREAD

**Issue by pixel32** [simpleapples/douban-analytics#2]
今天运行了一下，报错。求解决啊～目前市场上没有比这个更好用的统计了。

**Comment by simpleapples** [comment]
hi 谢谢你的鼓励 我把这个小工具重写成了一个chrome插件
访问 https://chrome.google.com/webstore/detail/oennkpmbcbppfhjknmfcgdgonofcgfbm
安装插件就可以用了
