### ISSUE TITLE
豆瓣修改了 api key 之后，已经失灵了

### ISSUE THREAD

**Issue by Demodi** [simpleapples/douban-analytics#3]
如题，有计划更新吗？
我加上了 apikey 有两个提示。跨域的不知道为何解决…求助，谢谢
DevTools failed to load SourceMap: Could not load content for chrome-extension://oennkpmbcbppfhjknmfcgdgonofcgfbm/js/axios.min.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

axios.min.js:8 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://api.douban.com/v2/book/user/46433029/collections?apikey=0df993c66c0c636e29ecbb5344252a4a&status=read&from=2019-07-01T00:00:00+08:00&to=2020-07-01T00:00:00+08:00 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by simpleapples** [comment]
Hi, 不好意思回复这么晚

我暂时没有计划更新（因为三个月前刚更新了一波，现在就坏了😂），最近事情比较多。

关于上面的报错看上去像是Chrome的安全策略修改了，可能需要找一下新的实现方式。

**Comment by Demodi** [comment]
没事没事。谢谢你的回复

**Comment by Demodi** [comment]
我试了你最新的代码是可以的。我之前有问题的是chrome上面的插件。现在可以了。感谢

**Comment by simpleapples** [comment]
嗯嗯 最新版发布时候没有通过审核 我当时也没处理😂
